#!/bin/bash
set -e

DATABASE_URL=${DATABASE_URL:11}
 
POSTGRES_USER=${DATABASE_URL%%:*}
POSTGRES_DB=${DATABASE_URL#*/}

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" <<-EOSQL
    DROP DATABASE IF EXISTS "$POSTGRES_DB";
    CREATE DATABASE "$POSTGRES_DB";
    GRANT ALL PRIVILEGES ON DATABASE "$POSTGRES_DB" TO $POSTGRES_USER;
EOSQL